name: 
  2.3.$(Rev:r)

trigger:
- master


parameters:

- name: test
  displayName: Pipeline Configuration
  type: string
  values:
    - none
    - one
    - true
  default: true


jobs:
- job: build
  displayName: Build and Test
  pool: 
      name: 'default'
      vmImage: 'SHALCHUK-NB'
  steps:
  - script: echo building $(Build.BuildNumber)
  - ${{ if eq(parameters.test, true) }}:

      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 5.9.1'
        inputs:
          versionSpec: 5.9.1

      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: '**/*.sln'
          feedsToUse: 'select'