name: 
  2.3.$(Rev:r)

trigger:
- master


parameters:

- name: test
  displayName: Pipeline Configuration
  type: string
  values:
    - 'None of the packages'
    - 'One of the packages (NuGet or Publish)'
    - 'Both packages (NuGet and Publush)'


jobs:

- job: build
  displayName: Build and Test
  pool: 
      name: 'default'
      vmImage: 'SHALCHUK-NB'
  steps:

  - ${{ if eq(parameters.test, 'None of the packages') }}:

      - script: echo Runnig - None of the packages
      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 5.9.1'
        inputs:
          versionSpec: 5.9.1
  
