trigger:
- master

pool:
  name: 'default'
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '4d32219b-dc62-4fba-98e9-9ec422654bea/c32e5ea0-6074-442c-80be-6f69f8828b3f'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
    
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '4d32219b-dc62-4fba-98e9-9ec422654bea/c32e5ea0-6074-442c-80be-6f69f8828b3f'