name: 
  2.3.$(Rev:r)

trigger:
- master

pool:
  name: 'default'
  vmImage: 'SHALCHUK-NB'


parameters:
- name: testEmpty
  values: 
    - Pidor
    - Ujeban
jobs:
  - job: A
    steps:
    - script: echo testEmpty is blank
    condition: eq(variables.testEmpty, 'Pidor')