name: 
  2.3.$(Rev:r)

trigger:
- master

pool: 
  name: 'default'
  vmImage: 'SHALCHUK-NB'
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  nupkgVersion: $(Build.BuildNumber)

parameters:

- name: NuGet
  displayName: NuGet Package Configuration
  type: string
  values:
    - 'Without Package Creation'
    - 'Package Creation ans Push'
    

- name: Publish
  displayName: Publish Package Configuration
  type: string
  values:
    - 'Without Package Creation'
    - 'Package Creation ans Push'


jobs:

- job: build
  displayName: Pipeline Configuration
  
  steps:
  - ${{ if and(eq (parameters.NuGet, 'Without Package Creation'), eq(parameters.Publish, 'Without Package Creation')) }}:
      - script: echo Runnig - None of the packages

   - ${{ if and(eq (parameters.NuGet, 'Package Creation ans Push'), eq(parameters.Publish, 'Package Creation ans Push')) }}:
      - script: echo Runnig - Both packages (NuGet and Publish)
    
      # - task: NuGetToolInstaller@0
      #     displayName: 'Use NuGet 5.9.1'
      #   inputs:
      #     versionSpec: 5.9.1