name: 
  2.3.$(Rev:r)

trigger:
- master


parameters:

- name: test
  displayName: Pipeline Configuration
  type: string
  values:
    - 'none'
    - 'one'
    - 'both'


jobs:
- job: build
  displayName: Build and Test
  pool: 
      name: 'default'
      vmImage: 'SHALCHUK-NB'
  steps:

  - script: echo building $(Build.BuildNumber)
  - ${{ if eq(parameters.test, 'none') }}:

      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 5.9.1'
        inputs:
          versionSpec: 5.9.1
  - ${{ if eq(parameters.test, 'none') }}: