pool:
  name: 'default'
  vmImage: 'SHALCHUK-NB'

parameters:

- name: test
  displayName: Run Tests?
  type: boolean
  default: false

trigger: none

jobs:
- job: build
  displayName: Build and Test
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(Build.BuildNumber)
  - ${{ if eq(parameters.test, true) }}:

      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 5.9.1'
        inputs:
          versionSpec: 5.9.1

      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: '**/*.sln'
          feedsToUse: 'select'