name: 
  2.3.$(Rev:r)

trigger:
- master

pool:
  name: 'default'
  vmImage: 'SHALCHUK-NB'


variables:
- name: testEmpty
  value: ''

jobs:
  - job: A
    steps:
    - script: echo testEmpty is blank
    condition: eq(variables.testEmpty, '')z